### ISSUE TITLE
Does not work properly when used within Visual Studio Code

### ISSUE THREAD

**Issue by alucryd** [1player/host-spawn#29] opened 2023-09-19 08:46 UTC
I'm trying to use fish inside the flatpak vscode, however it just exits after a few seconds without any error. Running bash or zsh works fine though, is there a way to debug the issue?
```
sh-5.1$ /run/host/usr/local/bin/host-spawn fish
[227 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[227 preload-host-spawn-strategy] Warning: waitpid override ignores groups
sh-5.1$
```

**Comment by alucryd** [comment] 2023-09-21 08:16
Yes my installation is fine, I use it everyday outside of flatpak. My vscode configuration is nothing special:
```
  "terminal.integrated.defaultProfile.linux": "bash",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "/var/run/host/usr/local/bin/host-spawn",
      "args": ["bash"]
    },
    "fish": {
      "path": "/var/run/host/usr/local/bin/host-spawn",
      "args": ["fish"]
    }
  },
```

**Comment by eclipseo** [comment] 2023-09-24 08:23
Have you tried this: https://github.com/flathub/com.visualstudio.code/issues/370#issuecomment-1721354814

**Comment by 1player** [comment] 2023-09-25 08:17
Can you please confirm if this issue only happens when used with VSCode, and whether it's reproducible in a toolbox or distrobox container? All seems to point to that being the case.

**Comment by 1player** [comment] 2023-09-25 08:22
Seems to be unrelated to host-spawn, and the issue linked by @eclipseo shows it affects other applications as well, and provides a workaround.  Closing for now, will reopen if there is evidence this is a host-spawn bug.

**Closed** 2023-09-25 08:22 UTC
